Add migration
vvkosty/go_ya_final pull request #1
Opened 2022-04-17 08:03 UTC by vvkosty

2022-05-02 08:29 UTC, ASPecherkin requested changes
Оставил несколько комментариев

2022-05-02 08:29 UTC, ASPecherkin commented on internal/app/integrations/accural_client.go
> +var ao AccrualOrder
а зачем использовать глобальный Ордер в функции 
```go
GetAccrualOrderData
```
возращает AccuralOrder?

2022-05-02 08:29 UTC, ASPecherkin commented on internal/app/storage/order.go
> +		if strings.Contains(err.Error(), "23505") {
а что обозначет такая ошибка?

2022-05-02 08:29 UTC, ASPecherkin commented on internal/app/storage/user.go
> +var user *UserModel
и зачем тут эта глобальная переменная?

2022-05-02 09:42 UTC, vvkosty commented on internal/app/integrations/accural_client.go
> +var ao AccrualOrder
верно, незачем, поправил

2022-05-02 09:43 UTC, vvkosty commented on internal/app/storage/order.go
> +		if strings.Contains(err.Error(), "23505") {
NewUniqueViolatesError проверка на уникальность

2022-05-02 09:49 UTC, vvkosty commented on internal/app/storage/user.go
> +var user *UserModel
ну я решил, что объявить переменную 1 раз и использовать ее, как контейнер в 2 функциях, идея хорошая) Или можно не заморачиваться и объявлять ее в каждой функции?

2022-05-04 09:29 UTC, ASPecherkin commented on internal/app/storage/user.go
> +var user *UserModel
можно объявлять в каждой функции, потому что GC всё равно её соберёт 

А про контейнер - обычно используют pool объектов, так как у тебя может более одного запроса и одна глобальная переменная скорее принесёт проблем, чем пользы

2022-05-04 09:30 UTC, ASPecherkin approved these changes
Глобальную переменную в user лучше поправить

2022-05-04 10:44 UTC, merged